/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    GoodsPagination: typeof import('./src/components/GoodsPagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopFooter: typeof import('./src/components/ShopFooter/ShopFooter.vue')['default']
    ShopHeader: typeof import('./src/components/ShopHeader/ShopHeader.vue')['default']
    TypeNav: typeof import('./src/components/TypeNav.vue')['default']
  }
}
